### ISSUE TITLE
change noise with cross_origin_auth

### ISSUE THREAD

**Issue by DavidS-ovm** [auth0/terraform-provider-auth0#1029]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Since a few days I'm getting the following changes for every auth0_client on every run:

```
  # auth0_client.efg will be updated in-place
  ~ resource "auth0_client" "efg" {
      - cross_origin_auth                     = true -> null
        id                                    = "abcd"
        name                                  = "efg"
        # (28 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
```

This is causing severe issues as terraform propagates the (presumed, but not actually) updated client values into the rest of our infrastructure.

### Expectation

No changes when nothing changes.

### Reproduction

Run terraform with this resource:

```terraform
resource "auth0_client" "efg" {
  name        = "efg"
  description = "Client used by efg"
  app_type    = "non_interactive"
}
```

### Auth0 Terraform Provider version

1.6.0

### Terraform version

1.9.5

**Comment by jordanjennings** [comment]
We're also very recently experiencing this same issue and we're on Auth0 provider v1.0.0

**Comment by hoppalotta** [comment]
Same issue here. I have [posted](https://community.auth0.com/t/action-required-update-applications-that-use-cross-origin-authentication/132819/11?u=badpracticemenolikey) in the auth0 community about this as well. 

Seems like this may have changed in the auth0 api without notice. The change described in the community thread does seem related, but the given change date of October 24, 2024 is about a month from today so that's odd.

**Comment by dan-cbm** [comment]
Also experiencing this, I can run `terraform apply` 5 times and the plan is the same each time :cry:

**Comment by kayleabox** [comment]
It seems that setting `crossOriginAuth` to `true` in cdktf is clearing up this diff for me.

**Comment by dan-cbm** [comment]
@kayleabox yes me as well in terraform I explicitly set `cross_origin_auth = true` on my `auth0_client` resource and it fixed the problem after a single `terraform apply`


my current version is:
````
provider "registry.terraform.io/auth0/auth0" {
  version     = "1.6.1"
  ````

**Comment by hoppalotta** [comment]
A [post](https://community.auth0.com/t/action-required-update-applications-that-use-cross-origin-authentication/132819/13?u=badpracticemenolikey) in the auth0 community forum indicates this is not a bug in the provider, but a change to a default in the auth0 api:

> If a application/client did not have cross_origin_authenication defined, a default value has been specified to match the value that you see in the Admin Dashboard. Previously this attribute (cross_origin_authentication) was not stored and exposed on the client object.

That post also notes:
> we will be removing cross_origin_auth to make this less confusing

If I'm reading this correctly, this may impact the `cross_origin_auth` argument on the `auth0_client` resource. the Is there any specific guidance on how this will impact the provider or how we can prepare when this deprecation takes place on October 25, 2024?

**Comment by leontastic** [comment]
Based on the docs, it looks like `cross_origin_auth` existed in many prior versions of this provider. I had this config specified for over 2 years and it was explicitly set to `false`. I remember noticing drift in the Terraform state when turning on cross origin authentication for one of my clients in December 2023 to see if embedded login still works (spoiler: it doesn't).

Now Terraform is reporting drift on every single client in my config:
```
      ~ cross_origin_auth                   = true -> false
```

I confirmed the option is turned on for all of these clients in the Dashboard as well. I am quite certain they were previously turned off.

Could someone from Auth0 confirm if there was an incident here that caused cross origin authentication to be turned on for all clients? This is mitigated by the presence of the CORS allowlist – but accidental and unexpected security config changes to all of my clients does not give me confidence in the security of the system.

**Comment by DavidS-ovm** [comment]
Hey folks, my account manager has advised me to contact Auth0 support to get this ticket prioritized with engineering. The current status is 

> I am just reaching out to update you that the internal ticket is still in progress.
>
> I will return as soon as any updates occur. 

from nine days ago on a ticket I opened three weeks ago. It might be useful if any customer on this ticket also contacted support pointing out that there is already an engineering ticket for this, and to add your weight (i.e. revenue) to that.

Thanks for listening.

**Comment by Inlustra** [comment]
Will also be reaching out and creating a ticket to get this sped up - so many useless changes appearing in our large monorepo tf

**Comment by duedares-rvj** [comment]
Hello guys,
Apologies for a delayed response on this one.

If the field is not in use, can we try setting `cross_origin_auth=false` and doing an apply. That should resolve the issue. 
Let us know how it goes.

**Comment by vanmash** [comment]
Hey,

we have the same issue. Why `terraform apply` does not remove `cross_origin_auth` from the state?

**Comment by duedares-rvj** [comment]
@vanmash It cannot explicitly remove the field from the state. Since it's part of the resource schema. 

I have tested this flow and here is my conclusion:
1. If we create a client and explicitly set `cross_origin_auth` to `true` or `false`, the same is retained in state.
2. If we create a client and DO NOT mention `cross_origin_auth`, since this is a boolean, it take the default value (which is false)
3. Now from here on, on every plan, it'd highlight that we are attempting to change `false` -> `null` (since we don't explicitly set a true/false but a null )
4. The ideal resolution to this is to EXPLICITLY set this value. Either true or false based on the use case in the resource definition. 

Please note that we have intentionally not specified a default value to `cross_origin_auth` in the schema. Because we'd like customer's to explicitly set it in their resource definitions. 

@Inlustra @leontastic @DavidS-ovm If there is any further specific use case or flow to reproduce the error on your end, we'd be happy to investigate it further.
ref: https://auth0.com/docs/troubleshoot/product-lifecycle/deprecations-and-migrations#update-applications-that-use-cross-origin-authentication

**Comment by vanmash** [comment]
You might be right with the schema.

However updating all the code with optional optional field with the default value just to _satisfy_ the provider does not bring much value.

In `azurerm` provider for example when a new optional field is introduced it is shown in the plan (with default value) and then saved to the state during apply. No change in the code is needed.
Also `- a_field = true --> null` means that it will be set to `null`, and gone from the plan after the apply.

I guess it would be great to have it like that or similar.

**Comment by leontastic** [comment]
@duedares-rvj We had our `cross_origin_auth` set to explicitly false for years, the git history shows it. We would regularly apply our configs, and the cross origin auth flag was definitely controlled by this field. Then one day our TF reported every single client saw this value drift to true.

This idea that "false is the default" does not take into account clients that previously existing clients all have this `cross_origin_auth` flag toggled to true now. I was astonished when I discovered this, and had to verify against the admin dashboard, because we had turned this off explicitly in our 50+ clients for security reasons.

My hypothesis on what happened: Auth0 deployed a change to toggle cross origin auth off for all new clients. In this change there was some kind of database migration which reset this preference for existing clients. And it turned it to TRUE for existing clients.

Look at all the past reports here and on the Auth0 community threads. Everyone is reporting their cross_origin_auth value for existing clients drifted to TRUE, not FALSE.

**Comment by acwest** [comment]
> You might be right with the schema.
> 
> However updating all the code with optional optional field with the default value just to _satisfy_ the provider does not bring much value.
> 
> In `azurerm` provider for example when a new optional field is introduced it is shown in the plan (with default value) and then saved to the state during apply. No change in the code is needed. Also `- a_field = true --> null` means that it will be set to `null`, and gone from the plan after the apply.
> 
> I guess it would be great to have it like that or similar.

Hi @vanmash , Im general, it would be possible to add the `Computed` marker to the attribute, but we have not done that in this case because the changed default is a security issue which we WANT the user to be informed of the change, so that they can explicitly decide to either keep the less secure value true value, or set it to false.

**Comment by leontastic** [comment]
It would have been in the weeks before the time of my original post at the beginning of October.

The problem is not that "it just gets switched back on apply" – because it does.

A product that promises security should not be creating drift in a security-sensitive config like cross origin auth. If it happens, the incident should be admitted and root cause analysis should be provided.

**Comment by acwest** [comment]
@leontastic , I believe I have found the original cause of your drift issue. It appears that at some point between January 2023 and October 2024 a change was made in one of our libraries in anticipation of a change in the Auth0 APIs regarding the naming of the cross_origin_auth property. https://community.auth0.com/t/action-required-update-applications-that-use-cross-origin-authentication/132819/11

**Comment by acwest** [comment]
Hi @leontastic, we did an RCA of the issue, and it was a bug in the implementation of `cross_origin_auth` attribute which has since been fixed.

**Comment by leontastic** [comment]
Amazing – thank you for the update @acwest and thank your team for their attention to this matter. It's not a critical issue for us because there are other layers of security besides this cross origin auth toggle. But care needs to be taken to avoid this type of incident lest it happens with more sensitive fields in the future.

**Comment by duedares-rvj** [comment]
Hello everyone,
Based on all the discussion we have had, I believe the noise around `cross_origin_auth` param can be handled by explicitly setting it.
Going ahead and closing this issue for now, feel free to re-open if the issue persists.
