### ISSUE TITLE
Unsure how to configure scopes for GitHub scopes with auth0_connection

### ISSUE THREAD

**Issue by mikroskeem** [auth0/terraform-provider-auth0#177]
### Describe the problem

I'm trying to configure GitHub connection to allow `read:user` and `read:org` scopes, but they don't seem to apply:

<img width="503" alt="image" src="https://user-images.githubusercontent.com/3490861/173197499-e98c8287-c882-49fb-af11-526d176180b0.png">

### What was the expected behavior?

`read:user` and `read:org` scopes to work.

### Reproduction

```terraform
resource "auth0_connection" "github" {
  name = "github"
  strategy = "github"
  options {
    client_id = "..."
    client_secret = "..."
    scopes = [
      "email",
      "read:org",
      "read:user"
    ]
  }
}
```

Applying succeeds, but trying to apply it 2nd time shows `read:org` and `read:user` to be added again.

### Environment

- **Version of `terraform-provider-auth0` used:** 0.30.3

**Comment by willvedd** [comment]
@mikroskeem This behavior isn't caused by a bug in the code but rather incorrect scope values. The available values for this block are: `admin_org`, `admin_public_key`, `admin_repo_hook`, `delete_repo`, `email`, `follow`, `gist`, `notifications`, `profile`, `public_repo`, `read_org`, `read_public_key`, `read_repo_hook`, `read_user`, `repo`, `repo_deployment`, `repo_status`, `write_org`, `write_public_key`, and  `write_repo_hook`. 

So for the example above it should instead be:

```terraform
resource "auth0_connection" "github" {
  name = "github"
  strategy = "github"
  options {
    client_id = "..."
    client_secret = "..."
    scopes = [
      "email",
      "read_user", # Note corrected value
      "read_org", # Note corrected value
     ]
  }
}
```

I've opened a [PR that updates the Github connection documentation](https://github.com/auth0/terraform-provider-auth0/pull/199) to better reflect this constraint.
