### ISSUE TITLE
Application must not have Token Endpoint Authentication Method

### ISSUE THREAD

**Issue by bgolding355** [auth0/terraform-provider-auth0#266]
### Describe the problem

We encountered this issue when applying a plan.
1. There did not appear to be any issue when the plan was generated
2. Running apply for this plan failed with:

   > Error: 400 Bad Request: Application must not have Token Endpoint Authentication Method set to "none" when client_credentials grant type is enabled

3. Searching for all of these on google yielded no relevant results
     * https://www.google.com/search?client=firefox-b-d&q=%22Application+must+not+have+Token+Endpoint+Authentication+Method%22
4. Searching auth0's documentation did not yield any actionable hits
    * https://auth0.com/docs/search?q=Application%20must%20not%20have%20Token%20Endpoint%20Authentication%20Method&page=1
6. Searching auth0's community forum did not yield any actionable hits
    * https://community.auth0.com/t/i-cannot-setup-password-in-auth0-dashboard/66297

### What was the expected behavior?

 
Either succeed, or there should be a page somewhere explaining how to resolve this (this ticket could suffice, but actual documentation would be better)

### Reproduction

1. have an auth0 tenant with an app_type of `spa`
3. have a terraform json with an `auth0_client` containing a map of app_types including the `spa`

If so, provide steps:

1. run `terraform plan` and see a vaguely reasonable plan
2. run `terraform apply` and get an error

### Environment

Please provide the following:

- terraform0.12.26
- **Version of `terraform-provider-auth0` used:** terraform-provider-auth0_v0.14.0_x4

**Comment by sergiught** [comment]
Hey @bgolding355 👋🏻 

Could you please provide a sample of the terraform config you're using to manage the auth0 client? 

The error you're getting is due to the fact that you're incorrectly trying to configure the application. If you want to manage a SPA Application you cannot use the client credentials grant type because SPA's are public applications and their Token Endpoint Authentication Method is set to None.

**Comment by bgolding355** [comment]
Hey @sergiught  :wave: 

We (@jsoref) are using a generator which creates nearly identical Terraform configuration for each of our tenants. 
```HCL
resource "auth0_client" "product_api_demo" {
        allowed_logout_urls                 = [
            "https://demo.example.com",
            "https://demo.example.com/home",
        ]
        allowed_origins                     = []
        app_type                            = "spa"
        callbacks                           = [
            "https://demo.example.com/callback",
            "https://demo.example.com/login",
        ]
        client_id                           = "auth0_provided_value"
        client_metadata                     = {}
        client_secret                       = (sensitive value)
        cross_origin_auth                   = false
        custom_login_page_on                = true
        encryption_key                      = {}
        grant_types                         = [
            "authorization_code",
            "implicit",
            "refresh_token",
            "client_credentials",
        ]
        id                                  = "auth0_provided_value"
      - initiate_login_uri                  = "https://demo.example.com/login" -> null
        is_first_party                      = true
        is_token_endpoint_ip_header_trusted = false
        name                                = "Demo product"
        oidc_conformant                     = false
        sso                                 = false
        sso_disabled                        = false
        token_endpoint_auth_method          = "none"
        web_origins                         = [
            "https://demo.example.com",
        ]

        jwt_configuration {
            lifetime_in_seconds = 36000
            scopes              = {}
            secret_encoded      = false
        }

        refresh_token {}
    }
```

Here is what I am seeing in `manage.auth0.com`

# All Apps are SPA's
## Broken Tenant App
![image](https://user-images.githubusercontent.com/60831565/183958304-12c79d73-b402-422f-8645-4028372574cd.png)

Note that the dropdown `Token Endpoint Authentication Method` is disabled.

![image](https://user-images.githubusercontent.com/60831565/183958445-c122643d-b47f-426d-9cce-b64e76ddf912.png)

## Non-complaining Tenant App
![image](https://user-images.githubusercontent.com/60831565/183959292-2423f486-1895-4bcf-a0f3-69e0d3edebef.png)

Note that the dropdown `Token Endpoint Authentication Method` is disabled.

![image](https://user-images.githubusercontent.com/60831565/183959450-7a119abb-34f8-4e91-8b7f-dd0c5281d0b6.png)

Note that this one appears to be identical to the preceding one, but is not complaining.

## Non-complaining and working Tenant App
![image](https://user-images.githubusercontent.com/60831565/183959969-eeabecf5-039a-422e-bb15-4f00f5ae6cc6.png)

Note that the dropdown `Token Endpoint Authentication Method` is NOT disabled and has a different value than the two above.

![image](https://user-images.githubusercontent.com/60831565/183960096-ec52e2bf-b5fe-48f8-a3e2-0dd32b7523e6.png)

Note that credential grants are set the same for all three. We don't seem to be able to change the check state of the client credentials grant.

Any guidance would be greatly appreciated!

**Comment by sergiught** [comment]
Hey @bgolding355 👋🏻  

The extra info and screenshots are very much appreciated! 👍🏻 

The issue is that you somehow ended up with wrongly configured applications (I'm assuming you used the management API endpoints directly to end up in that state?). 

As you see also from the dashboard you're not allowed to set the "Client Credentials" grant type to a SPA App and you're getting a warning also for having Token Endpoint Authentication Method as "Post". 

If you need the "Client Credentials" grant type and the Token Endpoint Authentication Method as "Post" you should not use a SPA App, but a Machine to Machine one or a Regular Web App.


### Now how do we fix this? 🤔 
- It depends on your use case... 👀 

### Option 1

If you need Token Endpoint Authentication Method as "Post" and the "Client Credentials" grant type, then your app type should not be SPA but Regular Web App or Machine to Machine (again, depends on your use case). 

You can use the API Explorer https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id after fetching an API Explorer Token from Applications -> APIs -> Auth0 Management API -> API Explorer and then patching the client (using it's ID) with something like `{"app_type":"regular_web"}` (Regular Web App) or `{"app_type":"non_interactive"} (M2M). 

### Option 2

You want the app type to be SPA, but then you'll need to remove the "Client Credentials" grant type and set Token Endpoint Authentication Method as "None". 

You can use the API Explorer https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id after fetching an API Explorer Token from Applications -> APIs -> Auth0 Management API -> API Explorer and then patching the client (using it's ID) with something like `{"token_endpoint_auth_method":"none", "grant_types":[]}`.

### Follow up questions

I'm curious however about this:

> We (@jsoref) are using a generator which creates nearly identical Terraform configuration for each of our tenants.

We don't have any Auth0 supported terraform generators, is this something you've built in house?

**Comment by sergiught** [comment]
Hey folks @bgolding355 , @jsoref, we haven't heard back from you and unfortunately this was not an actual issue with the auth0 provider but a misconfiguration that happened outside of the tool and thus we'll be closing this issue down. 

If something's unclear or if you're unable to correct the configuration and then manage the clients through the provider, please reply back here and we'll take a look together. 🙏🏻

**Comment by jsoref** [comment]
Hi @sergiught...

I'm currently spending my valuable time fighting this tooling and I'm not enjoying it.

This looks cute:
https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id

Except for the fact that it doesn't seem to have credentials or explain how to get them:

```
{
  "statusCode": 401,
  "error": "Unauthorized",
  "message": "Missing authentication"
}
```

I'm not sure I have the energy to file another ticket about that (I'm a prolific ticket filer, so when I run out of energy that means there's something really rotten).

---

The [`auth0-cli`](https://github.com/auth0/auth0-cli) faithfully reproduces the error that `auth0/terraform-provider-auth0` returns:
```
auth0 apps update $APP -g ''
```

```
Unable to update application $APP: 400 Bad Request: Application must not have Token Endpoint Authentication Method set to "none" when client_credentials grant type is enabled
```

And https://github.com/auth0/auth0-cli/search?q=%22Token+Endpoint+Authentication+Method%22 has 0 hits.

I acknowledge that it's a problem with a product, namely, the product your company produces with which your client interacts. Your client should be resilient to it, and if your client needs your employer to provide an extra api so that _this_ module is able to function without crashing, then I'm requesting that you file that request internally.

Until then, a public record showing this bug in every place that it occurs is better than a private ticket that no other customer will know about. And since you're an engineer at the company, you're much more likely to get this fixed than me trying to go through 3 layers of support.

To be clear: I am dealing w/ layer 2 of Auth0 support on a related issue, and they've recently apologized for their slow response times.

I think I will file _one_ ticket against the cli, since it seems like in theory if it were slightly more flexible it'd be enough to get me out of these woods.

**Comment by sergiught** [comment]
Hey @jsoref, 

I completely agree with you that it definitely should be not as painful. Your feedback is much appreciated and I'll see what I can do internally so we offer more guidance and prevent misconfiguration issues in the future. At the same time however I'm available to help fix your issue together. 

In my previous message I have posted instructions on how to get the access token needed for the API Explorer:

> You can use the API Explorer https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id **after fetching an API Explorer Token from Applications -> APIs -> Auth0 Management API -> API Explorer** and then patching the client (using it's ID) with something like {"token_endpoint_auth_method":"none", "grant_types":[]}.

However if you go to https://auth0.com/docs/api/management/v2#!/Clients/patch_clients_by_id and click on "Set API Token" (you can find this on the top left corner) it will also post a link inside that explains in more details how to get an Access Token for the Management API (this link: https://auth0.com/docs/secure/tokens/access-tokens/management-api-access-tokens). 

<img width="589" alt="image" src="https://user-images.githubusercontent.com/28300158/185654230-a6321678-d704-48af-8862-d5a2e294c2cc.png">

After obtaining the token and setting it on the API Explorer Page you can start using the UI to make the requests needed to correctly fix the configuration issues of your applications as described above in my message: https://github.com/auth0/terraform-provider-auth0/issues/266#issuecomment-1211763324. 

Let me know if you have any issues with this! Happy to help further.

**Comment by jsoref** [comment]
Yeah, I was able to figure it out, but the banging my head against a brick wall was not enjoyable.

After performing the suggested thing, the terraform now has different opinions. And my SPA was totally broken because it didn't have `implicit grant`. Once I added that back, the app returned to working.

Terraform is still totally broken though. It has a plan, I apply the plan, it says success, and I ask it to plan, it gives me the same plan as the original plan.

I'm not sure I can easily anonymize the output. Happy to share direct if there's a better approach.

**Comment by sergiught** [comment]
I know this is a big ask and it will require some more of your time, however it would be super helpful for us if you could share a detailed description of the infinite plan bug you're experiencing, as we really do want to fix this and improve yours and everyone else's lives using the provider 🙏🏻 . 

However a separate issue would be more suited so we can continue the discussion in a more focused way, also so it's more easily searchable by other folks that might experience the same issue. 

Any extra info you can provide ideally with the help of `TF_LOGS=debug terraform plan`, would be helpful. But of course please be mindful of obfuscating any sensitive data.
