### ISSUE TITLE
Tf Plan Error : invalid character '<' looking for beginning of value_

### ISSUE THREAD

**Issue by sergiught** [auth0/terraform-provider-auth0#36]
From terraform-provider-auth0 created by [rajdeeprspl](https://github.com/rajdeeprspl): alexkappa/terraform-provider-auth0#393  

Hi There,

Can you please help me on the below described issue ?

I am getting this error while applying terraform plan or trying to import resources.

`**_Error: invalid character '<' looking for beginning of value_**`

But executing terraform validate its showing validation success .

Same code with different credentials working for a tenant but not to other one.

Is it something that I am missing ?

```Terraform version : 0.14.6

auth0_connection.google: Importing from ID "con_xxxxxxxxxxxxx"...
auth0_connection.google: Import prepared!
  Prepared auth0_connection for import
auth0_connection.google: Refreshing state... [id=con_xxxxxxxxxx]

Error: invalid character '<' looking for beginning of value

```

[terraform.txt](https://github.com/alexkappa/terraform-provider-auth0/files/6473513/terraform.txt)

I am also attaching terraform trace log in here.

Many Thanks.

rajdeep

**Comment by sergiughf** [comment]
Hey @rajdeeprspl, would you be able to test with the latest version of the provider? v0.29.0?

**Comment by rajdeeprspl** [comment]
Okay @sergiughf , sure. I will do and let you know the consequence. Many Thanks!

**Comment by terrabitz** [comment]
We just ran into this issue too. There was a similar issue in the [DataDog Terraform provider repository](https://github.com/DataDog/terraform-provider-datadog/issues/364). According to [this comment](https://github.com/DataDog/terraform-provider-datadog/issues/364#issuecomment-558793230), this error results when a Go HTTP client is trying to parse an HTML page as JSON.

I suspect the root issue is that the Auth0 API is returning an HTML error page due to something like an invalid authentication token or a rate limit. Apart from fixing the Auth0 API to return JSON, one fix could be fixing the Go client to recognize when these errors occur, allowing it to return a more helpful error message.

**Comment by willvedd** [comment]
I've had a chance to look into this briefly. It sure appears that this is caused by an unexpected HTML response. However, I can confirm that under normal operating circumstances, the Management API _only_ returns a JSON payload. Granted, there may be certain situations like service disruptions and outages that present HTML, but I'm considering those to be exceptions. 

What's not clear is if this is an intermittent issue or not. Further, working with connections sometimes requires third-party integrations which introduces more potential points of failure. 

@terrabitz @rajdeeprspl Can you indicate if your issues are intermittent? Also can you provide sample connections that trigger this issue? Without being able to reproduce or have some additional diagnostic information, this issue isn't quite actionable.

**Comment by terrabitz** [comment]
@willvedd  This issue is very intermittent for us, so unfortunately there's no specific trigger I can provide. I agree, it definitely seems to be an odd exception/corner-case in the management API. 

I don't think this issue is solvable in this module per-say, but maybe adding more error context could help.

Instead of:

```
Error: invalid character '<' looking for beginning of value
```

Something like:

```
Error: couldn't parse invalid JSON response: invalid character '<' looking for beginning of value
```

I think that would make it abundantly clear that this is an unexpected response instead of, say, an unexpected `<` somewhere in the TF file.

**Comment by sergiught** [comment]
Hey folks, we've added the suggested improvements to https://github.com/auth0/go-auth0/releases/tag/v0.10.1 the underlying library used to make those HTTP requests. Once we bump the SDK version within the provider and create a new release you'll at least have an updated error message. Closing this down now.
