### ISSUE TITLE
Data Source for default google-oauth2

### ISSUE THREAD

**Issue by fmdaboville** [auth0/terraform-provider-auth0#364]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

According [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs/resources/connection#google-oauth2-connection) on the provider : 

![image](https://user-images.githubusercontent.com/32450687/195783036-50595c05-83c7-4f23-a6cc-f5a2a04569b7.png)

My tenant is configured with this connection.

I'm using the `auth0_client` ressource to create an application and the `google-oauth2-connection` is already created : 

![image](https://user-images.githubusercontent.com/32450687/195784254-ee2cca3e-a0a7-49ac-9198-4a45d400e436.png)

I want to disable this default connection for my client, so I'm trying to set an empty list of `enabled_clients` like this : 

```
resource "auth0_connection" "google_oauth2" {
  name            = "google-oauth2"
  strategy        = "google-oauth2"
  enabled_clients = []
}
```

But I'm getting this error since the name is the same : 

```
auth0_connection.google_oauth2: Creating...
╷
│ Error: 409 Conflict: A connection with the same name already exists
│ 
│   with auth0_connection.google_oauth2,
│   on main.tf line 185, in resource "auth0_connection" "google_oauth2":
│  185: resource "auth0_connection" "google_oauth2" {
│ 
╵
```

### Describe the ideal solution

It will be useful to have a Data Source `auth0_connection` to retrieve an existing connection and update it to be able to disable it on new clients.

**Comment by sergiught** [comment]
Hey @fmdaboville 👋🏻 

The issue you're having is that you're trying to apply before importing that connection as it already exists, assuming you want to keep the same name and connection.  

To fix it run:

```terminal
$ terraform import auth0_connection.google_oauth2 <insertConnectionIDHere>
$ terraform apply // this will now remove all enabled clients
```

Alternatively you can create multiple google_oauth2 connection types but they will have to have different names. e.g.

```
resource "auth0_connection" "google_oauth2" {
  name            = "new-google-oauth2"
  strategy        = "google-oauth2"
  enabled_clients = []
}
```



In terms of data sources, we have them on our roadmap and we'll tackle this very soon ~Q1 2023 (no exact ETA yet). 

And to simplify the developer experience when managing clients and connection associations we'll tackle this https://github.com/auth0/terraform-provider-auth0/issues/281 within Q4 2022. 

Because of this we'll close this issue down. But if you encounter any issues with the suggestions above, we'll reopen and help out! Thanks!

**Comment by aramkarapetian** [comment]
hi @sergiught,
I would like to re-open this issue as importing connection is not anyhow ideal.
If you are recovering or replicating entire setup this is forces to do manual action in the recovery process.

Currently tenant resource can wrap around existing tenant settings and will not require to import.
Can't this be implemented similarly?

Thank you

**Comment by sergiught** [comment]
Hey @aramkarapetian 👋🏻 

For resources that are singletons (only 1 available instance is ever made available) we went ahead and implemented the "smart import" where the import can determine if the resource already exists before trying to create it. 

However such logic isn't implementable for resources like the connections as these aren't singletons and an import needs to be made using the ID of the connection before trying to manage it.

**Comment by aramkarapetian** [comment]
@sergiught, I see the point, from technical perspective it makes lot of sense, just from IaC perspective this does not solve the problem. The auth0 via terraform is useless if you cannot replicate the setup without human intervention.
Isn't there a tradeoff?

For example an argument on the resource enabling smart result (can be done only for connection resource and for google).

I understand that the code will not be perfect but at the end UX what matters here or?

What do you think?

**Comment by sergiught** [comment]
I'm not sure I fully understand your issue @aramkarapetian. The terraform philosophy is that when a resource already exists, you need to import it first in order to manage it, this is not something auth0 provider specific. Once you import you can go ahead and manage it. 

Resources: https://developer.hashicorp.com/terraform/cli/import. 

If you have something more specific that goes wrong with the import please open another issue so we can have a focused discussion over there. 

Thanks!
