### ISSUE TITLE
auth0_connection_client plans without error but does not take effect

### ISSUE THREAD

**Issue by Schparky** [auth0/terraform-provider-auth0#403]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have created a resource using the new `auth0_connection_client` and it doesn't appear to be working. My connection and my client are in two Terraform Cloud workspaces, with the connection ID output from the "common" workspace for the "staging" workspace to use.

Common workspace:
```hcl
resource "auth0_connection" "passwordless" {
  name     = "Passwordless"
  strategy = "email"
}

output "auth0_passwordless_id" {
  value = auth0_connection.passwordless.id
}
```

Staging workspace:
```hcl
resource "auth0_connection_client" "passwordless" {
  connection_id = data.terraform_remote_state.common.outputs.auth0_passwordless_id
  client_id     = auth0_client.cam.id
}
```

For troubleshooting, after this failed to take effect, I tried moving the `auth0_connection_client` into the "common" workspace using a manually-supplied client ID. That, too, failed to take effect. And by "take effect", I mean that it doesn't show as enabled on the Auth0 dashboard and an API call to `/passwordless/start` fails with error: "connection is disabled (client_id: redacted - connection: email)".

![image](https://user-images.githubusercontent.com/3172830/203496089-623b63de-8802-4f9b-be5d-65e13ed77a45.png)

### Expectation

The passwordless connection should be enabled on the staging client application.

### Reproduction

As described above

### Auth0 Terraform Provider version

0.40.0

### Terraform version

1.3.5

**Comment by sergiught** [comment]
Hey @Schparky thanks for opening this. This is not actually a bug, let me explain what happens. 

The Auth0 Tenant will allow multiple email connections to be created through the Management API but the one you see in the passwordless connections tab:

![image](https://user-images.githubusercontent.com/28300158/164051794-a57ee6ad-7637-4589-9beb-f65bd6299aab.png)

in order for the UI to activate that, the connection name you're creating needs to be named "email" e.g. 

```hcl
resource "auth0_connection" "email" {
    name = "email"
    strategy = "email"
    enabled_clients = ["some_id_of_some_application/client"]
    is_domain_connection = true
}
```

So if you want to see that one enabled you'll have to have `name = "email"`

So if you already got that created, make sure to import that one. You can find the exact ID of it using the API Explorer https://auth0.com/docs/api/management/v2#!/Connections/get_connections and then re-apply the enabled clients ids and the toggle will get green. 

Let me know if you encounter any issues. 

PS: Also make sure you set all the properties the UI is requiring to afterwards open and edit the email connection from the UI, otherwise you'll get an error and the settings tab won't open.

**Comment by Schparky** [comment]
@sergiught thanks! I did this, importing the existing resources. Then I disabled it in the UI then ran/applied a new plan. It created the new connection and the change was visible in the UI. Thank you.
