### ISSUE TITLE
409 Conflict: There was an error creating branding settings

### ISSUE THREAD

**Issue by Nightapes** [auth0/terraform-provider-auth0#406]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Resource `auth0_branding_theme` is not working.
When adding the resource to terraform i get an 409 even on the first try, i also don't see any Themes in the auth0 UI

> │ Error: 409 Conflict: There was an error creating branding settings: theme already exists

If i try to import the default Theme first i get after changing the Theme

> │ Error: 400 Bad Request: Path validation error: 'Object didn't pass validation for format theme-id: default' on property themeId (The ID of the theme).

### Expectation

Setting a custom theme or updating the default Theme should work without any error. 

### Reproduction

1. Create `auth0_branding_theme`
2. Run Terraform apply

### Auth0 Terraform Provider version

v0.40.0

### Terraform version

v1.3.3

**Comment by danmcgee-soda** [comment]
We hit this same issue this morning as well. Ultimately, we realized we could work around it. It seems that auth0 is using `default` as a read-only alias to the underlying theme ID, but writes are rejected.

If you look at the payload returned from `/api/branding/themes/default`, you'll see a `themeID` property in the JSON document. If you import using this ID, rather than `default`, everything starts working and you can make updates to the theme via code.

**Comment by Nightapes** [comment]
@danmcgee-soda thanks for the workaround. It worked

For Auth0:
I think it should work without the need to import the default theme first. We have multiple tenants and is a little bit annoying to import the theme for every tenant.

**Comment by sergiught** [comment]
Hey folks, thanks for opening the issue and for providing a workaround @danmcgee-soda ! 👍 

At the moment we can only ever have 1 branding theme created and active, thus the 409 when trying to create another one without importing the already created one in the dashboard. 

As this is a singleton resource we can further enhance the behavior of the resource to directly update the branding theme when one is found, instead of trying to create another one. 

I'll mark this however as an enhancement / feature rather than a bug. 

I don't have an exact ETA for when we can improve this, but most likely in mid/end of Q1.

**Comment by sergiught** [comment]
Hey folks 👋🏻 ,

We simplified management of this resource to no longer force a user to import the resource if already existing in the latest release: https://registry.terraform.io/providers/auth0/auth0/0.44.0/docs.

Thanks again for raising awareness of this! 🙏🏻 

If you encounter any issues with this release please let us know.
