### ISSUE TITLE
Flow support for Actions 

### ISSUE THREAD

**Issue by kkdeveloper7** [auth0/terraform-provider-auth0#73]
I went over the resources on https://registry.terraform.io/providers/auth0/auth0/latest/docs and was unable to find a resource where I will be able to put created action `auth0_action` into flow. 

Is there a planned roadmap to support this resource? 

For example: 
1. Create `post-login` action 
2. Create flow where `post-login`  action will be used. 

Thank you!

**Comment by michielvangendt** [comment]
Hi!

The `auth0_trigger_binding` resource can bind an action into a flow. The documentation contains a nice example, but feel to ask any questions you might have here!

**Comment by sergiughf** [comment]
Hey @kkdeveloper7 thanks for opening this issue, as @michielvangendt mentioned (thanks a lot 🙇🏻 ) this is already available within the provider under the `auth0_trigger_binding` resource. I'll be closing this issue down because of this but feel free to reopen in case you're encountering issues using the resource.

**Comment by kkdeveloper7** [comment]
Thank you. I was not sure if it was a proper resource to use since actions are the replacement for the trigger for my understanding,
