### ISSUE TITLE
resource "auth0_client"

### ISSUE THREAD

**Issue by itskornbailey** [auth0/terraform-provider-auth0#763]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/terraform-provider-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://registry.terraform.io/providers/auth0/auth0/latest/docs) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/terraform-provider-auth0/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/terraform-provider-auth0/releases/latest) of this provider and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Migrating from v0.50 to v1.0 and ran into this bug/issue.

resource auth0_client 

is error with the following **Error: missing expected [**

<img width="581" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/26728086/2cd873e0-8991-4347-b568-8c873495eb6a">

here is a example of my code after changing to the v1 and changing the addons samlp logout syntax and removed the "="

<img width="618" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/26728086/8e557c4c-902e-4d32-b438-2bf41f74ff4c">

My statefile is now throwing these errors aswell...
is there a known issue with auth0_client resource going from v0.50 to v1?

<img width="592" alt="image" src="https://github.com/auth0/terraform-provider-auth0/assets/26728086/ae8ec3c7-91ac-4b98-b155-bcb1195e7c7e">

This did not occur in v0.50 and it doesn't look like the addon syntax has changed much besides the logout argument block.

I checked the documentation for auth0_client, and the addons doesnt seem to need [ ] only { }.
https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.0/docs/resources/client
please assist.

Is the beta version ready? The only reason for migration is the node16/18 string update. 
thank you much

### Expectation

Expecting the auth0_client resources to behave the same as in v.0.50.

### Reproduction

use v0.50 to create auth0_client resource with addons such as logout.
then migrate to v1.0

the statefile and code errors out.

### Auth0 Terraform Provider version

v1.0 beta

### Terraform version

v1.5.4

**Comment by sergiught** [comment]
Hey @itskornbailey 👋🏻 

We've followed up with a fix for this in https://registry.terraform.io/providers/auth0/auth0/1.0.0-beta.1. Please make sure you update the version in your terraform configs:

```
terraform {
  required_providers {
    auth0 = {
      source  = "auth0/auth0"
       version = "1.0.0-beta.1"
    }
  }
}
```

If you're upgrading and are already managing an existing `auth0_client` resource please check the migration guide: https://github.com/auth0/terraform-provider-auth0/blob/main/MIGRATION_GUIDE.md#client-addons, specifically before upgrading, run a `terraform state rm auth0_client.<resource_name>.` Then upgrade to `v1.0.0-beta.1` and re-import the client resource using `terraform import auth0_client.<resource_name> <client_id>`. This is needed due to the fact that the addon types have been better typed, thus changing as well how we store these settings within the state.

Let us know if you have any other issues! Much appreciated again for the beta feedback! 🙇🏻

**Comment by itskornbailey** [comment]
thanks
