### ISSUE TITLE
Universal Login UX improvements

### ISSUE THREAD

**Issue by scott-rr** [auth0/terraform-provider-auth0#912]
### Checklist

- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Hey there! Big fan of the implementation of the new universal login experience and the ability to customize. While I was working on some customization for my org, I discovered a few UX improvements to the customization options that I would really love without needing to go code an entire custom HTML solution. 

The first is that there is no way to style the background color of the secondary button in the universal login. It would be great if there was a `secondary_button` option in the colors schema, similar to how the `primary_button` works.

It also doesn't seem like there is a way to turn off some of the text options in the universal login. For example, we don't want our login to also include a sign up link, but the only way to stop that from rendering is by replacing the text with a space ` `. Although it visually seems to be no longer included, the space is still rendered on the prompt as a hyperlink and there are errors in the UI if nothing is included (see screenshot).

There's also an accessibility bug when you re-arrange the order of the social buttons to be above the login inputs. When tabbing through the form, these seem to retain a tabIndex of their original location (see video).

<img width="937" alt="Screenshot 2024-01-24 at 10 02 57 AM" src="https://github.com/auth0/terraform-provider-auth0/assets/144359875/c6dc0f04-b0ea-4bda-9e90-3e57a85d75dc">
https://github.com/auth0/terraform-provider-auth0/assets/144359875/05431e53-bac0-40d8-8ccf-19be5b41b874

### Describe the ideal solution

- Ability to style the background of the secondary button
- Ability to not include certain pieces of text on a prompt
- Correct tab order in prompts

**Comment by willvedd** [comment]
Hi @scott-rr thanks for taking the time to provide this feedback. It does not appear to be related to the Terrafrom Provider however.

Does this issue pertain to the universal login customization provided by the Auth0 CLI ([related](https://auth0.github.io/auth0-cli/auth0_universal-login_customize.html))? If so, please recreate this issue in the [Auth0 CLI repo](https://github.com/auth0/auth0-cli).

Otherwise, if this is feedback with the Auth0 product itself, I highly recommend you create a post in the [Auth0 Community Forum](https://community.auth0.com/). There are dedicated Auth0 support professionals who are much more equipped to respond.
